version: '3.9'

services:
  jdbc-mysql:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: shop
    volumes:
      - ./dbdata:/var/lib/mysql
    ports:
      - 3307:3306